name: Featurebranch
on:
  push:
    branches-ignore:
      - 'master'
      - 'develop'
      - '*android*'
      - 'githubActionsRefactoring'
jobs:
  # ==========================================================================
  # Build all x86 Linux flavours
  buildLinux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ CentOS/Dockerfile, Debian/Dockerfile_Buster, Debian/Dockerfile_Stretch, Fedora/Dockerfile, OpenSUSE/Dockerfile, Ubuntu/Dockerfile_18_04, Ubuntu/Dockerfile_20_04 ]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build docker images
        run: docker build -t local -f Docker/${{ matrix.distro }}_noUpload --build-arg BUILD_THREADS=2 .
        env:
          GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ==========================================================================
  # Build aarch64 version (Raspberry PI ARMv8)
  buildARM:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [ RaspberryPi/Dockerfile_Buster]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - name: Build docker images
        run: docker build -t local -f Docker/${{ matrix.distro }}_noUpload --build-arg BUILD_THREADS=2 .
        env:
          GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ==========================================================================
  # Build MacOS version
  buildMacOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.10'
          setup-python: 'false'
          modules: 'qtwebengine'
      - name: Install dependencies
        run: |
          curl -L https://bintray.com/homebrew/bottles/download_file?file_path=boost-1.74.0.high_sierra.bottle.tar.gz -o boost-1.74.0.high_sierra.bottle.tar.gz
          brew install -f boost-1.74.0.high_sierra.bottle.tar.gz
          brew install berkeley-db@4
      - name: Build MacOS binaries
        run: ./scripts/cmake-build-mac.sh -g
        env:
          MAC_QT_DIR: ${{ env.Qt5_DIR }}
          BOOST_VERSION_MAC: 1.74.0

  # ==========================================================================
  # Build Windows version
  buildWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.9'
          setup-python: 'false'
          modules: 'qtwebengine'
      - name: Install vcpkg and packages with cache
        uses: lukka/run-vcpkg@v6
        with:
          vcpkgArguments: 'berkeleydb boost leveldb openssl'
          vcpkgGitCommitId: a037d826492039db9d58af47a1e1248037d15f40
          vcpkgTriplet: x64-windows
      - name: Build Windows binaries
        run: ./scripts/cmake-build-win.bat
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows
          QTDIR: ${{ env.Qt5_Dir }}
          VSDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise'
          CMAKEDIR: 'C:\Program Files\CMake\bin'
          VCPKGDIR: ${{ github.workspace }}/vcpkg
