name: Develop
on:
  push:
    branches:
      - develop
      - master

jobs:
  # ==========================================================================
  # Create Github tag/release and export short SHA of current HEAD
  prepareRelease:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.url }}
      github_sha_short: ${{ steps.slug.outputs.sha8 }}
      alias_release: ${{ steps.determine_release.outputs.alias_release }}
    steps:
      - uses: actions/checkout@v1
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      - name: Set Alias release/tag name
        id: determine_release
        run: |
          if [[ ${{ steps.extract_branch.outputs.branch }} = master ]] ; then
              majorVersion=$(grep CLIENT_VERSION_MAJOR ${{ github.workspace }}/CMakeLists.txt | head -n1 | cut -d ' ' -f2 | sed 's/)//g' | tr -d '\\n' | tr -d '\\r' | sed 's/ //g')
              minorVersion=$(grep CLIENT_VERSION_MINOR ${{ github.workspace }}/CMakeLists.txt | head -n1 | cut -d ' ' -f2 | sed 's/)//g' | tr -d '\\n' | tr -d '\\r' | sed 's/ //g')
              bugfixVersion=$(grep CLIENT_VERSION_REVISION ${{ github.workspace }}/CMakeLists.txt | head -n1 | cut -d ' ' -f2 | sed 's/)//g' | tr -d '\\n' | tr -d '\\r' | sed 's/ //g')
              echo "::set-output name=alias_release::$(printf '%s.%s.%s' $majorVersion $minorVersion $bugfixVersion)"
          else
              echo "::set-output name=alias_release::Build${{ github.run_number }}"
          fi

      # First create the plain release, so the upload URL could be exported
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.determine_release.outputs.alias_release }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # If we're on 'master', use ReleaseNotes.md
      - name: Releasenotes from master
        id: create_release_master
        uses: softprops/action-gh-release@v1
        if: steps.extract_branch.outputs.branch == 'master'
        with:
          tag_name: ${{ steps.determine_release.outputs.alias_release }}
          name: "Release ${{ steps.determine_release.outputs.alias_release }} (Build #${{ github.run_number }})"
          body_path: ${{ github.workspace }}/ReleaseNotes.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # If we're on 'develop', use simple text directly
      - name: Releasenotes from Develop
        id: create_release_develop
        uses: softprops/action-gh-release@v1
        if: steps.extract_branch.outputs.branch != 'master'
        with:
          tag_name: ${{ steps.determine_release.outputs.alias_release }}
          name: "Continuous build #${{ github.run_number }}"
          body: |
            Build #${{ github.run_number }} from ${{ steps.date.outputs.date }}
            - To verify checksums see dedicated checksum files for each download
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ==========================================================================
  # Build all x86 Linux flavours
  buildLinux:
    runs-on: ubuntu-latest
    needs: prepareRelease
    strategy:
      matrix:
        distro: [
            CentOS/Dockerfile,
            Debian/Dockerfile_Buster,
            Debian/Dockerfile_Buster_i386,
            Debian/Dockerfile_Stretch,
            Fedora/Dockerfile,
            OpenSUSE/Dockerfile,
            Ubuntu/Dockerfile_18_04,
            Ubuntu/Dockerfile_18_04_i386,
            Ubuntu/Dockerfile_20_04
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Build docker images
        run: >
          docker build
          -t local
          -f Docker/${{ matrix.distro }}
          --build-arg BUILD_THREADS=2
          --build-arg GITHUB_CI_TOKEN=${{ secrets.GITHUB_TOKEN }}
          --build-arg GIT_COMMIT=${{ needs.prepareRelease.outputs.github_sha_short }}
          --build-arg ALIAS_RELEASE=${{ needs.prepareRelease.outputs.alias_release }}
          --build-arg REPLACE_EXISTING_ARCHIVE=--replace
          .
        env:
          GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ==========================================================================
  # Build aarch64 version (Raspberry PI ARMv8)
  buildARM:
    runs-on: ubuntu-latest
    needs: prepareRelease
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: arm64
      - name: Build docker images
        run: >
          docker build
          -t local
          -f Docker/RaspberryPi/Dockerfile_Buster
          --build-arg BUILD_THREADS=2
          --build-arg GITHUB_CI_TOKEN=${{ secrets.GITHUB_TOKEN }}
          --build-arg GIT_COMMIT=${{ needs.prepareRelease.outputs.github_sha_short }}
          --build-arg ALIAS_RELEASE=${{ needs.prepareRelease.outputs.alias_release }}
          --build-arg REPLACE_EXISTING_ARCHIVE=--replace
          .
        env:
          GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # ==========================================================================
  # Build MacOS version
  buildMacOS:
    runs-on: macos-latest
    needs: prepareRelease
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.10'
          setup-python: 'false'
          modules: 'qtwebengine'

      - name: Install dependencies
        run: |
          curl -L https://bintray.com/homebrew/bottles/download_file?file_path=boost-1.74.0.high_sierra.bottle.tar.gz -o boost-1.74.0.high_sierra.bottle.tar.gz
          brew install -f boost-1.74.0.high_sierra.bottle.tar.gz
          brew install berkeley-db@4

      - name: Cache build dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-build-dependencies-mac
        with:
          path: |
            ${{ github.workspace }}/cmake-build-cmdline-mac/*
            !${{ github.workspace }}/cmake-build-cmdline-mac/aliaswallet
            ~/Archives/Tor/Tor.libraries.MacOS.zip
          key: ${{ runner.os }}-${{ env.cache-name }}

      - name: Build MacOS binaries
        run: ./scripts/cmake-build-mac.sh -g
        env:
          MAC_QT_DIR: ${{ env.Qt5_DIR }}
          BOOST_VERSION_MAC: 1.74.0

      - name: Create MacOS dmg sha256 checksum file
        run: |
          shasum -a 256 ${{ github.workspace }}/cmake-build-cmdline-mac/aliaswallet/Alias.dmg | awk '{ print $1 }' > ${{ github.workspace }}/cmake-build-cmdline-mac/aliaswallet/Alias.sha256
          cat ${{ github.workspace }}/cmake-build-cmdline-mac/aliaswallet/Alias.sha256

      - name: Upload MacOS Build
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/cmake-build-cmdline-mac/aliaswallet/Alias.dmg
          asset_name: Alias-${{ needs.prepareRelease.outputs.alias_release }}-${{ needs.prepareRelease.outputs.github_sha_short }}-Mac.dmg
          tag: ${{ needs.prepareRelease.outputs.alias_release }}
          overwrite: true

      - name: Upload MacOS checksum file
        id: upload-release-checksum
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/cmake-build-cmdline-mac/aliaswallet/Alias.sha256
          asset_name: Alias-${{ needs.prepareRelease.outputs.alias_release }}-${{ needs.prepareRelease.outputs.github_sha_short }}-Mac.sha256
          tag: ${{ needs.prepareRelease.outputs.alias_release }}
          overwrite: true

  # ==========================================================================
  # Build Windows version
  buildWindows:
    runs-on: windows-latest
    needs: prepareRelease
    outputs:
      upload_url: ${{ needs.prepareRelease.outputs.upload_url }}
      github_sha_short: ${{ needs.prepareRelease.outputs.github_sha_short }}
      alias_release: ${{ needs.prepareRelease.outputs.alias_release }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.9'
          setup-python: 'false'
          modules: 'qtwebengine'

      - name: Install vcpkg and packages with cache
        uses: lukka/run-vcpkg@v6
        with:
          vcpkgArguments: 'berkeleydb boost leveldb openssl'
          vcpkgGitCommitId: a037d826492039db9d58af47a1e1248037d15f40
          vcpkgTriplet: x64-windows

      - name: Build Windows binaries
        run: ./scripts/cmake-build-win.bat
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows
          QTDIR: ${{ env.Qt5_Dir }}
          VSDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise'
          CMAKEDIR: 'C:\Program Files\CMake\bin'
          VCPKGDIR: ${{ github.workspace }}/vcpkg

      - name: Create zip archive and sha256 checksum
        run: |
          powershell Compress-Archive build/Alias Alias.zip
          powershell "(Get-FileHash Alias.zip).Hash > Alias.sha256"
          powershell "(Get-Content Alias.sha256) | Out-File Alias.sha256 -Encoding ascii"
          type Alias.sha256

      - name: Upload Windows Build
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/Alias.zip
          asset_name: Alias-${{ needs.prepareRelease.outputs.alias_release }}-${{ needs.prepareRelease.outputs.github_sha_short }}-Win64.zip
          tag: ${{ needs.prepareRelease.outputs.alias_release }}
          overwrite: true

      - name: Upload Windows checksum file
        id: upload-release-checksum
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/Alias.sha256
          asset_name: Alias-${{ needs.prepareRelease.outputs.alias_release }}-${{ needs.prepareRelease.outputs.github_sha_short }}-Win64.sha256
          tag: ${{ needs.prepareRelease.outputs.alias_release }}
          overwrite: true

  # ==========================================================================
  # Create Windows installer
  # Based on the content of https://github.com/aliascash/installer
  createWindowsInstaller:
    runs-on: windows-latest
    needs: buildWindows
    steps:
      # Get installer repo content
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          repository: aliascash/installer

      # Download installable content...
      - name: Download content to install
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: https://github.com/aliascash/alias-wallet/releases/download/${{ needs.buildWindows.outputs.alias_release }}/Alias-${{ needs.buildWindows.outputs.alias_release }}-${{ needs.buildWindows.outputs.github_sha_short }}-Win64.zip
          file-name: Alias.zip
          location: ${{ github.workspace }}

      # ... and extract it
      - name: Extract content to install
        run: 7z x -o"${{ github.workspace }}/windows/content" "${{ github.workspace }}/Alias.zip"

      # Create installer
      - name: Create Windows installer
        uses: joncloud/makensis-action@v3.4
        with:
          arguments: "/V4"
          additional-plugin-paths: "${{ github.workspace }}/windows/plugins"
          script-file: "windows/Alias.nsi"

      - name: Create installer checksum file
        run: |
          powershell "(Get-FileHash ${{ github.workspace }}/windows/Alias-Installer.exe).Hash > ${{ github.workspace }}/windows/Alias-Installer.sha256"
          powershell "(Get-Content ${{ github.workspace }}/windows/Alias-Installer.sha256) | Out-File ${{ github.workspace }}/windows/Alias-Installer.sha256 -Encoding ascii"
          type ${{ github.workspace }}/windows/Alias-Installer.sha256

      # Upload the installer to Github
      - name: Upload installer
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/windows/Alias-Installer.exe
          asset_name: Alias-${{ needs.buildWindows.outputs.alias_release }}-${{ needs.buildWindows.outputs.github_sha_short }}-Win64-Installer.exe
          tag: ${{ needs.buildWindows.outputs.alias_release }}
          overwrite: true

      - name: Upload installer checksum
        id: upload-release-checksum
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/windows/Alias-Installer.sha256
          asset_name: Alias-${{ needs.buildWindows.outputs.alias_release }}-${{ needs.buildWindows.outputs.github_sha_short }}-Win64-Installer.sha256
          tag: ${{ needs.buildWindows.outputs.alias_release }}
          overwrite: true
